project_id: "473186"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

languages_mapping: &languages_mapping
  locale:
    "es-ES": "es"

files:
  [
    {
      source: "/website/i18n/en/**/*",
      translation: "/website/i18n/%locale%/**/%original_file_name%",
      languages_mapping: *languages_mapping,
    },
    {
      source: "/docs/**/*",
      translation: "/website/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%",
      languages_mapping: *languages_mapping,
      ignore:
        [
          "/docs/virtual",
          "/docs/tsconfig.json",
          "/docs/assets",
          "/docs/package.json",
          "/docs/node_modules",
        ],
    },
  ]
